name: Update gist with rings view
on:
  push:
    paths-ignore:
      - '**.md'
    branches:    
      - main
      
jobs:
  update-gist:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Update Gist
        run: |
          swift run RingsCLI -i rings.png -o rings.jpg
          [ -f rings.jpg ] && echo "$FILE exist." || echo "$FILE does not exist."
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone "https://user:${GH_TOKEN}@gist.github.com/${GIST_TOKEN}.git" gist
          mv image.jpg gist
          cd gist
          git add image.jpg
          git commit -m "Update image"
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
